allowBuilds:
  workerd: true
  esbuild: true

catalog:
  '@sveltejs/kit': next

minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.69'
  - '@ai-sdk/openai@4.0.52'
  - '@ai-sdk/provider-utils@5.0.34'
  - '@ai-sdk/provider@4.0.9'
  - '@ai-sdk/svelte@5.0.85'
  - ai@7.0.85

overrides:
  'better-auth>@sveltejs/kit': 'catalog:'
  'auth>@sveltejs/kit': 'catalog:'
  'execa': '8.0.1'
