-- Certifier descriptions backfill (14 bodies). Grounded in existing name/country/standard rows.
UPDATE certifying_bodies SET description='Jabatan Kemajuan Islam Malaysia — the Malaysian government authority behind MS 1500:2019. Its halal certificate is the most widely recognised in the world and a common import requirement across the Middle East and ASEAN.', updated_at=1788900000 WHERE id='jakim';
UPDATE certifying_bodies SET description='Badan Penyelenggara Jaminan Produk Halal — Indonesia''s statutory halal assurance agency. Since October 2024, food and beverage products sold in Indonesia must carry BPJPH certification under Law 33/2014, with fatwa support from MUI (Majelis Ulama Indonesia).', updated_at=1788900000 WHERE id='bpjph';
UPDATE certifying_bodies SET description='Majlis Ugama Islam Singapura — Singapore''s Islamic Religious Council. It runs a voluntary certification scheme (MUIS-HC-S001) trusted well beyond the city-state; many buyers treat MUIS certification as a premium signal.', updated_at=1788900000 WHERE id='muis';
UPDATE certifying_bodies SET description='Saudi Food and Drug Authority — the regulator for food imports into Saudi Arabia. Halal consignments need SFDA-recognised certification plus product registration in the SFDA e-portal before shipment.', updated_at=1788900000 WHERE id='sfda';
UPDATE certifying_bodies SET description='Ministry of Industry and Advanced Technology (UAE) — runs the Emirates halal conformity scheme under UAE.S 2055-1 and issues the optional Halal National Mark licence as an additional trust signal.', updated_at=1788900000 WHERE id='moiat';
UPDATE certifying_bodies SET description='Islamic Food and Nutrition Council of America — the best-known US halal certifier. IFANCA certificates are accepted by JAKIM, MUI and Gulf authorities, making it the default choice for North American exporters.', updated_at=1788900000 WHERE id='ifanca';
UPDATE certifying_bodies SET description='Turkish halal certification association applying OIC/SMIIC 1:2019. GIMDES runs a strict voluntary scheme popular with manufacturers targeting OIC markets from a Turkish base.', updated_at=1788900000 WHERE id='gimdes';
UPDATE certifying_bodies SET description='South African National Halaal Authority — the major halal certifier in Southern Africa, applying OIC/SMIIC-aligned requirements for domestic and export supply chains.', updated_at=1788900000 WHERE id='sanha';
UPDATE certifying_bodies SET description='Saudi Standards, Metrology and Quality Organization (SASO) and its SABER conformity platform. Food imports must satisfy GSO 2055-1 halal requirements alongside SABER product registration.', updated_at=1788900000 WHERE id='saber';
UPDATE certifying_bodies SET description='Central Islamic Council of Thailand — the sole Thai body issuing the national HAL-TH halal mark, with 200,000+ certified items. Thailand''s export credibility for halal food rests on CICOT certification.', updated_at=1788900000 WHERE id='cicot';
UPDATE certifying_bodies SET description='Pakistan Halal Authority — the federal body developing Pakistan''s formal halal certification infrastructure around PS OIC/SMIIC standards, alongside a fast-growing meat export sector.', updated_at=1788900000 WHERE id='pha';
UPDATE certifying_bodies SET description='Halal Food Authority (UK) — a British halal certifier applying an OIC/SMIIC-aligned scheme, serving UK manufacturers and exporters to Gulf and Southeast Asian markets.', updated_at=1788900000 WHERE id='hfa';
UPDATE certifying_bodies SET description='Helal Akreditasyon Kurumu — Türkiye''s governmental halal accreditation body. HAK accredits certification bodies against OIC/SMIIC standards rather than certifying products directly.', updated_at=1788900000 WHERE id='hak';
UPDATE certifying_bodies SET description='Australia-based halal certification body (NHASA) applying GSO-aligned requirements for Australian meat and food exporters serving Middle Eastern and Asian markets.', updated_at=1788900000 WHERE id='nhasa';
