import { drizzle } from 'drizzle-orm/d1';
import * as schema from './schema';

const now = new Date();

// ==================== Market Guides Seed ====================
export const marketGuidesSeed = [
	{
		slug: 'indonesia',
		country: 'Indonesia',
		flag: '\u{1F1EE}\u{1F1E9}',
		region: 'Southeast Asia',
		muslimPopulation: '~230 million',
		totalPopulation: '~275 million',
		marketSizeUsd: '$220B+ (halal products)',
		mandateStatus: 'mandatory',
		mandatorySince: 'October 2024 (F&B)',
		certifyingBodies: [
			{ slug: 'bpjph', name: 'BPJPH' },
			{ slug: 'lppom-mui', name: 'LPPOM MUI' }
		],
		importRequirements: [
			'Halal certificate from BPJPH-recognized foreign halal certification body (FHCB)',
			'Certificate must be issued by a body recognized under mutual recognition (MR) with BPJPH',
			'JAKIM-issued certificates accepted under Indonesia\u2013Malaysia MR arrangement',
			'Product registration via SIHALAL digital platform',
			'Labeling in Bahasa Indonesia with halal logo (segel halal)'
		],
		standardBasis: 'HAS 23000 (Indonesia), aligned with OIC/SMIIC standards',
		certificateValidity: '4 years (no changes in raw materials/process)',
		estimatedCostUsd: 'IDR 300,000 processing fee (SME-subsidized); regular scheme varies by product',
		processingTime: '3\u20136 months',
		keyInsights: [
			"World's largest Muslim population \u2014 the single biggest halal consumer market",
			'Law 33/2014 (amended 2023) mandates halal certification for F&B; cosmetics and pharma phasing in next',
			'SMEs receive government subsidies \u2014 IDR 300,000 flat processing fee',
			'SIHALAL platform digitized the entire application and verification process',
			'AI Halal tool (aihalal.halal.go.id) provides product pre-analysis'
		],
		opportunities: [
			'Mandatory compliance created a certification rush \u2014 huge demand for consultants and certifiers',
			'Domestic production cannot meet demand for premium halal imports (dairy, meat, ingredients)',
			'Halal tourism and modest fashion are fast-growing adjacent sectors',
			'E-commerce halal grocery segment growing 20%+ annually'
		],
		challenges: [
			'Registration through SIHALAL can be slow without local representation',
			'BPJPH recognition of foreign certifiers is required \u2014 not all bodies qualify',
			'Import licensing (through BPOM/other agencies) runs parallel to halal registration',
			'Decentralized enforcement at port level can cause inconsistent clearance'
		],
		summary: "The world's largest halal market by population and the regulatory anchor of Southeast Asia. Since October 2024, halal certification is mandatory for all food and beverage products \u2014 imports included \u2014 making Indonesia both the biggest opportunity and the most complex compliance destination.",
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		slug: 'malaysia',
		country: 'Malaysia',
		flag: '\u{1F1F2}\u{1F1FE}',
		region: 'Southeast Asia',
		muslimPopulation: '~20 million',
		totalPopulation: '~34 million',
		marketSizeUsd: '$80B+ (halal industry ecosystem)',
		mandateStatus: 'mandatory',
		mandatorySince: 'Long-established (Trade Descriptions Act 2011)',
		certifyingBodies: [
			{ slug: 'jakim', name: 'JAKIM' }
		],
		importRequirements: [
			'JAKIM halal certificate or certificate from JAKIM-recognized foreign certification body (FHCB)',
			'JAKIM maintains the reference list of recognized certifiers worldwide',
			'Halal certification mandatory for meat, poultry imports regardless of origin',
			'Import license (AP) required for meat and poultry products',
			'Malay/English labeling with certifier logo'
		],
		standardBasis: 'MS 1500 (Malaysia), referencing OIC/SMIIC and Codex halal guidelines',
		certificateValidity: '2 years (food premises); 1 year (abattoirs); 3 years (logistics/cosmetics/pharma); 5 years for clean 5+ year holders',
		estimatedCostUsd: '$2,000\u20135,000+ depending on audit scope and facility',
		processingTime: '3\u20136 months',
		keyInsights: [
			'JAKIM certification is the global gold standard \u2014 accepted in Middle East, ASEAN, most OIC states',
			"Malaysia chairs OIC/SMIIC standardization \u2014 strong influence on global halal norms",
			'Double certification pathway: JAKIM for domestic, FHCB recognition for foreign suppliers',
			'Halal Industry Master Plan 2030 targets Malaysia as the global halal hub',
			"MIHAS trade show is world's largest halal exhibition (50,000+ visitors)"
		],
		opportunities: [
			'Most efficient gateway market \u2014 JAKIM cert opens doors across OIC',
			'Halal park ecosystem (over 20 dedicated halal industrial parks)',
			'Strong demand for certified ingredients, flavors, and food tech',
			'Islamic finance integration \u2014 financing options for halal ventures'
		],
		challenges: [
			'JAKIM audit wait times can stretch 6+ months',
			'High competition \u2014 mature market with many certified players',
			'Cost of maintaining annual audits for abattoir/food premise categories',
			'Bahasa Malaysia documentation required for certain categories'
		],
		summary: "The gold-standard halal jurisdiction. A JAKIM certificate is the most widely accepted halal credential in international trade, and Malaysia's regulatory maturity makes it the reference market for halal standards worldwide.",
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		slug: 'uae',
		country: 'United Arab Emirates',
		flag: '\u{1F1E6}\u{1F1EA}',
		region: 'Middle East',
		muslimPopulation: '~9 million',
		totalPopulation: '~11 million',
		marketSizeUsd: '$120B+ (halal trade hub value)',
		mandateStatus: 'mandatory',
		mandatorySince: '2014 (ESMA halal scheme)',
		certifyingBodies: [
			{ slug: 'esma', name: 'ESMA / MOIAT' }
		],
		importRequirements: [
			'UAE halal scheme accreditation (UAE.S 2055-1/2055-2) for meat, poultry, supplements, nutraceuticals',
			'Certificates from ESMA-accredited bodies (JAKIM, MUI, IFANCA accepted under accreditation)',
			'Product must be certified before customs clearance for regulated categories',
			'Arabic labeling required on all food products',
			'Halal National Mark available as an additional trust signal'
		],
		standardBasis: 'UAE.S 2055-1 (halal food requirements), UAE.S 2055-2 (management systems), GCC-wide recognition',
		certificateValidity: '1 year',
		estimatedCostUsd: '$3,000\u20138,000 including accreditation and audit',
		processingTime: '3\u20138 weeks',
		keyInsights: [
			'Dubai is the re-export hub \u2014 60%+ of halal imports are re-exported to GCC/Africa/CIS',
			'UAE Halal National Mark goes beyond basic certification \u2014 stronger consumer trust signal',
			'ESMA (now MOIAT) accredits certification bodies rather than certifying directly at scale',
			'Gateway to the wider GCC \u2014 single accreditation unlocks Saudi, Qatar, Kuwait, Bahrain, Oman trade',
			"Gulfood (world's largest F&B expo) drives annual sourcing cycles"
		],
		opportunities: [
			'Re-export model means one UAE entry point serves 2B+ consumers across MENA, Africa, CIS',
			'Free zone logistics infrastructure (Jebel Ali) for halal warehousing',
			'Fast-growing halal tourism, hospitality, and airline catering sectors',
			"Dubai's Halal Cluster in DMCC dedicated to halal businesses"
		],
		challenges: [
			'1-year validity means annual renewal cost and audit cycle',
			'Strict import controls at port level \u2014 rejections common without correct documentation',
			'Animal-origin ingredients in cosmetics/supplements face extra scrutiny',
			'Arabic labeling and documentation requirements add cost'
		],
		summary: "The strategic re-export hub of the global halal trade. UAE accreditation unlocks the entire GCC and serves as the distribution gateway to the Middle East, Africa, and CIS markets.",
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		slug: 'saudi-arabia',
		country: 'Saudi Arabia',
		flag: '\u{1F1F8}\u{1F1E6}',
		region: 'Middle East',
		muslimPopulation: '~32 million',
		totalPopulation: '~36 million',
		marketSizeUsd: '$95B+ (domestic halal consumption)',
		mandateStatus: 'mandatory',
		mandatorySince: '2018 (SFDA halal regulation)',
		certifyingBodies: [
			{ slug: 'sfda', name: 'SFDA' },
			{ slug: 'gac', name: 'GAC' }
		],
		importRequirements: [
			'Halal certificate from SFDA-recognized certification body',
			'Product registration in SFDA e-portal before shipment',
			'Valid Certificate of Conformity (CoC) for food imports',
			'Arabic labeling mandatory',
			'Meat/poultry: Islamic slaughter certificate with government countersignature from origin country'
		],
		standardBasis: 'SFDA halal regulations; GCC Standardization Organization (GSO) halal standards',
		certificateValidity: '1 year (product registration)',
		estimatedCostUsd: '$2,800\u20136,000',
		processingTime: '6\u201312 weeks',
		keyInsights: [
			"Largest consumer market in the GCC \u2014 imports 80%+ of its food",
			'SFDA regulates directly \u2014 no self-certification or voluntary pathway for food',
			"Saudi Halal Expo (Riyadh) is MENA's largest dedicated halal trade show",
			'Vision 2030 invests in domestic halal production \u2014 import substitution accelerating',
			'Islamic slaughter certificates for meat require government-to-government countersignature'
		],
		opportunities: [
			'Massive import dependency creates sustained demand across all food categories',
			'Food security programs actively recruiting foreign suppliers and investors',
			'Halal cosmetics and pharma sectors growing 15%+ annually',
			'Hajj/Umrah pilgrimage food services \u2014 10M+ visitors annually'
		],
		challenges: [
			'SFDA e-portal registration can be slow without local importer support',
			'Violations carry severe penalties including blacklisting',
			'Shipment-level rejections common if documentation mismatches product',
			'Local distributor requirement for market entry in practice'
		],
		summary: "The largest and most import-dependent halal market in the Gulf. SFDA regulation is strict but well-documented \u2014 compliant suppliers find Saudi Arabia among the most rewarding halal destinations.",
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		slug: 'turkiye',
		country: 'T\u00FCrkiye',
		flag: '\u{1F1F9}\u{1F1F7}',
		region: 'Europe',
		muslimPopulation: '~75 million',
		totalPopulation: '~85 million',
		marketSizeUsd: '$60B+ (halal food consumption)',
		mandateStatus: 'voluntary',
		mandatorySince: '',
		certifyingBodies: [
			{ slug: 'gimdes', name: 'GIMDES' },
			{ slug: 'smiic', name: 'SMIIC (HQ)' }
		],
		importRequirements: [
			'Halal certificate from TSE or GIMDES for halal-labeled products (voluntary but commercially expected)',
			'Standard Turkish Food Codex labeling requirements',
			'No blanket halal mandate \u2014 but halal claims must be backed by valid certification',
			'Meat imports restricted to approved countries and establishments'
		],
		standardBasis: 'TSE halal standards (OIC/SMIIC 1), aligned with OIC harmonized standards',
		certificateValidity: '1\u20133 years depending on certifier and category',
		estimatedCostUsd: '$2,000\u20134,000',
		processingTime: '8\u201316 weeks',
		keyInsights: [
			'T\u00FCrkiye holds the OIC/SMIIC secretariat \u2014 the country writes the OIC-wide halal rulebook',
			"World Halal Council general assembly and mutual recognition decisions made at Istanbul's World Halal Summit",
			'Halal Expo Istanbul draws 50,000+ visitors and 500+ exhibitors each November',
			'Domestic market largely halal by default \u2014 certification is about export credibility',
			'Bridge position between European production standards and OIC market access'
		],
		opportunities: [
			'Gateway for European manufacturers targeting OIC markets',
			'Certification accepted across OIC/SMIIC member states',
			'Strong food processing and export infrastructure',
			'Halal tourism sector booming \u2014 4M+ Muslim visitors to Istanbul alone'
		],
		challenges: [
			'Voluntary regime means market fragmentation \u2014 some buyers accept TSE, others demand GIMDES or foreign certs',
			'Economic volatility affects pricing and payment reliability',
			'Halal and secular market segments coexist \u2014 certification messaging must be targeted',
			'Currency fluctuation complicates long-term contracts'
		],
		summary: "The standards-setter. T\u00FCrkiye chairs OIC/SMIIC and hosts the World Halal Summit \u2014 its certification decisions shape mutual recognition for the entire OIC market of 1.9 billion consumers.",
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		slug: 'pakistan',
		country: 'Pakistan',
		flag: '\u{1F1F5}\u{1F1F0}',
		region: 'South Asia',
		muslimPopulation: '~220 million',
		totalPopulation: '~240 million',
		marketSizeUsd: '$70B+ (halal food market)',
		mandateStatus: 'phasing-in',
		mandatorySince: '',
		certifyingBodies: [
			{ slug: 'psqca', name: 'PSQCA' },
			{ slug: 'hsa', name: 'HSA (Halal Standards Authority)' }
		],
		importRequirements: [
			'Halal certificate required for meat and derived products',
			'PSQCA conformity for food imports',
			'Import authorization via PSW (Pakistan Single Window)',
			'Urdu or English labeling'
		],
		standardBasis: 'PS 3733 (Pakistan halal standard), aligned with OIC/SMIIC',
		certificateValidity: '1 year',
		estimatedCostUsd: '$1,500\u20133,000',
		processingTime: '8\u201312 weeks',
		keyInsights: [
			"World's second-largest Muslim population \u2014 nearly all consumption is halal by default",
			'Emerging formal certification infrastructure \u2014 PSQCA halal standard PS 3733 adopted 2018',
			'Major meat exporter (beef to GCC, Vietnam) \u2014 export-side certification growth strong',
			'Government targeting halal export growth under Trade Policy Framework',
			'Large informal sector \u2014 formal certification penetration still low'
		],
		opportunities: [
			'Export-oriented meat certification is a high-growth service niche',
			'Domestic formalization creating first-mover certification demand',
			'Low production costs make Pakistan a competitive halal sourcing base',
			'CPEC corridor links Chinese ingredient suppliers to Gulf markets'
		],
		challenges: [
			'Regulatory enforcement capacity still developing',
			'Documentation and customs efficiency below regional peers',
			'Only a handful of recognized halal certifiers \u2014 bottleneck risk',
			'Buyers often require additional third-party audits beyond local certification'
		],
		summary: "A high-potential halal production base and the world's second-largest Muslim consumer market, where formal halal certification infrastructure is now emerging to match its enormous scale.",
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		slug: 'usa',
		country: 'United States',
		flag: '\u{1F1FA}\u{1F1F8}',
		region: 'North America',
		muslimPopulation: '~4.5 million',
		totalPopulation: '~335 million',
		marketSizeUsd: '$20B+ (domestic halal market)',
		mandateStatus: 'voluntary',
		mandatorySince: '',
		certifyingBodies: [
			{ slug: 'ifanca', name: 'IFANCA' },
			{ slug: 'hfsaa', name: 'HFSAA' },
			{ slug: 'halal-watch', name: 'Halal Watch World' }
		],
		importRequirements: [
			'FDA registration and Prior Notice for food imports',
			'FSMA compliance (Food Safety Modernization Act)',
			'Halal certification voluntary \u2014 but required by retailers/consumers for halal-claimed products',
			'No government halal regulation \u2014 private certifier ecosystem',
			'English labeling with FDA nutrition facts panel'
		],
		standardBasis: 'Private certifier standards (IFANCA most widely recognized); no federal halal standard',
		certificateValidity: '1 year (typical)',
		estimatedCostUsd: '$4,000\u201310,000 (annual)',
		processingTime: '8\u201316 weeks',
		keyInsights: [
			'1.4 million Muslim-majority households with above-average purchasing power',
			'Halal market growing 15%+ annually \u2014 faster than general food market',
			'No federal halal law \u2014 8+ states have truth-in-halal-labeling statutes',
			'IFANCA is the dominant certifier \u2014 recognized by JAKIM, MUI, ESMA and most import authorities',
			'Halal mainstreaming: Costco, Walmart, Kroger now stock halal-certified lines'
		],
		opportunities: [
			'Non-Muslim consumers increasingly buy halal for perceived quality/ethics (halal-adjacent market)',
			'Amazon/retail e-commerce simplifies national distribution',
			'Ethnic food service sector (halal restaurants) expanding beyond metro cores',
			'Export-side: US halal-certified products well-accepted in OIC markets'
		],
		challenges: [
			'No unified standard \u2014 certifier choice affects which export markets open',
			'Annual audit costs are relatively high for SMEs',
			'Halal fraud incidents damaged consumer trust \u2014 buyers demand reputable certifiers',
			'Fragmented consumer market across metro areas'
		],
		summary: "The most commercially mature voluntary halal market, where private certifiers govern a fast-growing $20B sector driven by mainstream retail adoption and a high-income Muslim consumer base.",
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	}
];

// ==================== Trade Shows Seed ====================
export const tradeShowsSeed = [
	{
		id: 'mihas-2026',
		name: 'MIHAS 2026 \u2014 Malaysia International Halal Showcase',
		city: 'Kuala Lumpur',
		country: 'Malaysia',
		region: 'Asia',
		startDate: '2026-09-23',
		endDate: '2026-09-26',
		venue: 'Malaysia International Trade and Exhibition Centre (MITEC)',
		website: 'https://mihas.my',
		scale: 'mega',
		description: "World's largest halal trade fair. Hosted by Malaysia's MITI and organised by MATRADE with JAKIM and HDC. Covers 14 halal industry clusters including food, pharma, Islamic finance, modest fashion, technology, and logistics.",
		focus: ['Food & Beverage', 'Pharmaceuticals', 'Islamic Finance', 'Modest Fashion', 'Technology', 'Logistics'],
		exhibitors: 1200,
		visitors: 50000,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'gulfood-2027',
		name: 'Gulfood 2027 \u2014 32nd Edition',
		city: 'Dubai',
		country: 'UAE',
		region: 'Middle East',
		startDate: '2027-02-22',
		endDate: '2027-02-26',
		venue: 'Dubai World Trade Centre',
		website: 'https://gulfood.com',
		scale: 'mega',
		description: "World's largest food and beverage exhibition. Major halal sourcing hub connecting buyers from Middle East, Africa, and South Asia with global suppliers.",
		focus: ['Food & Beverage', 'Halal Products', 'Dairy', 'Meat', 'Confectionery'],
		exhibitors: 5000,
		visitors: 100000,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'halal-expo-istanbul-2026',
		name: '11th OIC Halal Expo 2026 & World Halal Summit',
		city: 'Istanbul',
		country: 'T\u00FCrkiye',
		region: 'Europe',
		startDate: '2026-11-25',
		endDate: '2026-11-28',
		venue: 'Istanbul Expo Center (\u0130FM)',
		website: 'https://ifm.com.tr',
		scale: 'mega',
		description: 'Most politically significant halal industry event. Co-located with World Halal Summit and World Halal Council general assembly. T\u00FCrkiye holds OIC/SMIIC secretariat. Covers mutual recognition agreements between certification bodies globally.',
		focus: ['Certification', 'Standards', 'OIC Trade', 'Food', 'Cosmetics', 'Pharmaceuticals'],
		exhibitors: 500,
		visitors: 50000,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'saudi-halal-expo-2026',
		name: 'Saudi International Halal Expo & Summit 2026',
		city: 'Riyadh',
		country: 'Saudi Arabia',
		region: 'Middle East',
		startDate: '2026-10-04',
		endDate: '2026-10-06',
		venue: 'Riyadh International Convention & Exhibition Center (RICEC)',
		website: 'https://saudihalalexp.com',
		scale: 'large',
		description: "MENA region's largest dedicated halal industry exhibition. Covers food, pharmaceuticals, cosmetics, modest fashion, tourism, and Islamic finance.",
		focus: ['Food', 'Pharmaceuticals', 'Cosmetics', 'Modest Fashion', 'Islamic Finance'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'halal-expo-canada-2026',
		name: 'Halal Expo Canada 2026',
		city: 'Toronto',
		country: 'Canada',
		region: 'North America',
		startDate: '2026-06-15',
		endDate: '2026-06-17',
		venue: 'Metro Toronto Convention Centre',
		website: 'https://halalexpo.ca',
		scale: 'large',
		description: "North America's core halal B2B platform. Attracts exhibitors from Malaysia, Turkey, UAE, Pakistan alongside North American producers targeting 1.4 million Muslim-majority households.",
		focus: ['Food & Beverage', 'B2B Matching', 'North American Market'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'jakarta-halal-expo-2026',
		name: 'Jakarta Halal Expo & Conference 2026',
		city: 'Tangerang',
		country: 'Indonesia',
		region: 'Asia',
		startDate: '2026-08-28',
		endDate: '2026-08-30',
		venue: 'Indonesia Convention Exhibition (ICE BSD City)',
		website: 'https://jakartahalalexp.com',
		scale: 'large',
		description: "Indonesia's flagship halal trade event. World's largest Muslim population market. Covers fashion, halal products, tourism, lifestyle, and Islamic finance.",
		focus: ['Fashion', 'Halal Products', 'Tourism', 'Lifestyle', 'Islamic Finance'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'mihas-dubai-2026',
		name: 'MIHAS @ Dubai 2026',
		city: 'Dubai',
		country: 'UAE',
		region: 'Middle East',
		startDate: '2026-11-16',
		endDate: '2026-11-18',
		venue: 'Dubai World Trade Centre',
		website: 'https://mihasdubai.com',
		scale: 'large',
		description: 'International edition of MIHAS. Showcases 200+ Malaysian halal suppliers to GCC and Middle Eastern buyers.',
		focus: ['Malaysian Products', 'GCC Market', 'B2B Matching'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'qatar-halal-expo-2026',
		name: 'Qatar Halal Expo & Conference 2026',
		city: 'Doha',
		country: 'Qatar',
		region: 'Middle East',
		startDate: '2026-09-07',
		endDate: '2026-09-09',
		venue: 'Doha Exhibition and Convention Center (DECC)',
		website: 'https://qatarhalalexp.com',
		scale: 'medium',
		description: "Qatar's dedicated halal trade platform. Growing market driven by FIFA 2022 legacy infrastructure and Vision 2030.",
		focus: ['Food', 'Hospitality', 'Islamic Finance'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'halal-japan-expo-2026',
		name: 'Halal Japan Expo 2026',
		city: 'Tokyo',
		country: 'Japan',
		region: 'Asia',
		startDate: '2026-04-15',
		endDate: '2026-04-17',
		venue: 'Tokyo Big Sight',
		website: 'https://halaljapan.jp',
		scale: 'medium',
		description: "Japan's halal trade event connecting halal exporters with Japanese importers and retailers. Growing demand for halal products in Japan's tourism and retail sectors.",
		focus: ['Food', 'Tourism', 'Japanese Market'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'halal-expo-nigeria-2026',
		name: 'Halal Expo Nigeria 2026',
		city: 'Lagos',
		country: 'Nigeria',
		region: 'Africa',
		startDate: '2026-02-18',
		endDate: '2026-02-20',
		venue: 'Eko Hotel & Suites',
		website: 'https://halalexponigeria.com',
		scale: 'regional',
		description: "West Africa's halal trade platform. Nigeria has Africa's largest Muslim population and growing halal demand.",
		focus: ['Food', 'Agriculture', 'West African Market'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'world-halal-summit-2026',
		name: 'World Halal Summit 2026',
		city: 'Istanbul',
		country: 'T\u00FCrkiye',
		region: 'Europe',
		startDate: '2026-11-25',
		endDate: '2026-11-27',
		venue: 'Istanbul Expo Center',
		website: 'https://worldhalalsummit.org',
		scale: 'large',
		description: 'Global summit on halal standards, certification, and policy. World Halal Council general assembly determines mutual recognition agreements between certification bodies.',
		focus: ['Certification', 'Standards', 'Policy', 'Mutual Recognition'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'global-halal-summit-2026',
		name: 'Global Halal Summit (GHaS) 2026',
		city: 'Kuala Lumpur',
		country: 'Malaysia',
		region: 'Asia',
		startDate: '2026-09-21',
		endDate: '2026-09-22',
		venue: 'MITEC',
		website: 'https://ghas.my',
		scale: 'large',
		description: 'Co-located with MIHAS. Global summit on halal industry trends, standards, and market access.',
		focus: ['Industry Trends', 'Standards', 'Market Access'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'anuga-halal-2027',
		name: 'Anuga \u2014 Anuga Halal Market 2027',
		city: 'Cologne',
		country: 'Germany',
		region: 'Europe',
		startDate: '2027-10-09',
		endDate: '2027-10-13',
		venue: 'Koelnmesse',
		website: 'https://anuga.com',
		scale: 'mega',
		description: "World's largest food and beverage trade fair with dedicated Halal Market section. 7,000+ exhibitors from 200+ countries.",
		focus: ['Food & Beverage', 'European Market', 'Global Sourcing'],
		exhibitors: 7000,
		visitors: 150000,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'philippines-halal-expo-2026',
		name: 'Philippines Halal Expo 2026',
		city: 'Manila',
		country: 'Philippines',
		region: 'Asia',
		startDate: '2026-11-20',
		endDate: '2026-11-22',
		venue: 'World Trade Center Manila',
		website: 'https://philippinehalalexp.com',
		scale: 'regional',
		description: "Philippines' halal trade platform. Growing Southeast Asian halal market with strong Muslim-majority southern regions.",
		focus: ['Food', 'Halal Certification', 'ASEAN Market'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'vietnam-halal-expo-2026',
		name: 'Vietnam Halal Expo 2026',
		city: 'Ho Chi Minh City',
		country: 'Vietnam',
		region: 'Asia',
		startDate: '2026-11-18',
		endDate: '2026-11-20',
		venue: 'Saigon Exhibition & Convention Center (SECC)',
		website: 'https://vietnamhalalexp.com',
		scale: 'regional',
		description: "Vietnam's halal trade event. Emerging halal manufacturing hub targeting ASEAN and OIC markets.",
		focus: ['Manufacturing', 'ASEAN Market', 'Export'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'france-halal-expo-2026',
		name: 'France Halal Expo 2026',
		city: 'Paris',
		country: 'France',
		region: 'Europe',
		startDate: '2026-11-24',
		endDate: '2026-11-26',
		venue: 'Paris-Nord Villepinte',
		website: 'https://francehalalexp.com',
		scale: 'medium',
		description: "Europe's largest halal consumer market event. France has 5+ million Muslim consumers.",
		focus: ['Consumer Products', 'European Market', 'Food & Beverage'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'india-halal-expo-2026',
		name: 'India International Halal Expo 2026',
		city: 'New Delhi',
		country: 'India',
		region: 'Asia',
		startDate: '2026-02-20',
		endDate: '2026-02-22',
		venue: 'Pragati Maidan',
		website: 'https://indiahalalexp.com',
		scale: 'large',
		description: "India's halal trade platform. World's third-largest Muslim population market with growing halal industry.",
		focus: ['Food', 'Cosmetics', 'Pharmaceuticals', 'Indian Market'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'halfest-malaysia-2026',
		name: 'HALFEST \u2014 Halal Fiesta Malaysia 2026',
		city: 'Kuala Lumpur',
		country: 'Malaysia',
		region: 'Asia',
		startDate: '2026-08-14',
		endDate: '2026-08-16',
		venue: 'MITEC',
		website: 'https://halfest.my',
		scale: 'medium',
		description: "Malaysia's consumer halal festival. B2C focused with food tasting, product launches, and consumer engagement.",
		focus: ['Consumer Products', 'Food', 'Lifestyle'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'adife-abu-dhabi-2026',
		name: 'Abu Dhabi International Food Exhibition (ADIFE) 2026',
		city: 'Abu Dhabi',
		country: 'UAE',
		region: 'Middle East',
		startDate: '2026-12-09',
		endDate: '2026-12-11',
		venue: 'Abu Dhabi National Exhibition Centre',
		website: 'https://adife.ae',
		scale: 'large',
		description: "Abu Dhabi's international food exhibition. Major sourcing event for Middle Eastern and North African food markets.",
		focus: ['Food & Beverage', 'Middle East Market', 'Halal Sourcing'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	},
	{
		id: 'halal-expo-germany-2026',
		name: 'Halal Expo Germany 2026',
		city: 'Frankfurt',
		country: 'Germany',
		region: 'Europe',
		startDate: '2026-11-12',
		endDate: '2026-11-14',
		venue: 'Messe Frankfurt',
		website: 'https://halalexpo-deutschland.de',
		scale: 'medium',
		description: "Central Europe's halal trade platform. Growing audience of Central European buyers with no prior dedicated halal event.",
		focus: ['European Market', 'Food', 'B2B Matching'],
		exhibitors: null,
		visitors: null,
		metaTitle: '',
		metaDescription: '',
		keywords: '',
		status: 'active',
		createdAt: now,
		updatedAt: now
	}
];

// ==================== Seed Function ====================
export async function seed(db: ReturnType<typeof drizzle<typeof schema>>) {
	await db.insert(schema.marketGuides).values(marketGuidesSeed);
	await db.insert(schema.tradeShows).values(tradeShowsSeed);
}
